---
- name: homebrew | update Homebrew package index
  community.general.homebrew:
    update_homebrew: true

- name: homebrew | install core CLI formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_formulae }}"
