HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt SHARE_HISTORY EXTENDED_HISTORY HIST_IGNORE_DUPS HIST_IGNORE_SPACE HIST_VERIFY

autoload -Uz compinit && compinit

export EDITOR="code --wait"
export FZF_DEFAULT_OPTS="--color=16"

# Long listings with eza: ll, and la with hidden files too.
alias ll='eza -l --git --group-directories-first'
alias la='eza -la --git --group-directories-first'

eval "$(mise activate zsh)"
source <(fzf --zsh)

eval "$(starship init zsh)"

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

eval "$(zoxide init zsh)"

[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
